function [BW, maskedRGBImage] = maskUnivRemove(RGB, colorSpace, maskThresLis)
    %createMask  Threshold RGB image using auto-generated code from colorThresholder app.
    %  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
    %  auto-generated code from the colorThresholder App. The colorspace and
    %  minimum/maximum values for each channel of the colorspace were set in the
    %  App and result in a binary mask BW and a composite image maskedRGBImage,
    %  which shows the original RGB image values under the mask BW.

    % Auto-generated by colorThresholder app on 15-May-2018
    %------------------------------------------------------

    % Convert RGB image to chosen color space
    I = colorSpace;

    channel1Min = maskThresLis(1);
    channel1Max = maskThresLis(2);
    channel2Min = maskThresLis(3);
    channel2Max = maskThresLis(4);
    channel3Min = maskThresLis(5);
    channel3Max = maskThresLis(6);

    % Create mask based on chosen histogram thresholds
    % gt: remove the part outside of the region [min, max]
    sliderBW = ...
        ((I(:, :, 1) >= channel1Max) | (I(:, :, 1) <= channel1Min)) & ...
        ((I(:, :, 2) >= channel2Max) | (I(:, :, 2) <= channel2Min)) & ...
        ((I(:, :, 3) >= channel3Max) | (I(:, :, 3) <= channel3Min));
    BW = sliderBW;

    % Initialize output masked image based on input image.
    maskedRGBImage = RGB;

    % Set background pixels where BW is false to zero.
    maskedRGBImage(repmat(~BW, [1 1 3])) = 0;

end
